"""Football Republic public package API."""

from .advanced_ecosystem import (
    AdvancedClubWorld,
    ContinentalChampionsCup,
    ContinentalSummary,
    ContractMarket,
    ContractRecord,
    DomesticCup,
    KnockoutResult,
    LoanRecord,
    WorkloadManager,
    WorkloadReport,
)
from .campaign import Campaign, PresidentialPlan, STRATEGIES, Strategy, run_strategy
from .deep_campaign import DeepCampaign, run_deep_strategy
from .deep_scenario import build_deep_2026_scenario
from .domain import Club, NationalFootballSystem, Region
from .ecosystem import (
    AdministrationRecord,
    ClubPyramid,
    ClubPyramidWorld,
    DivisionLeague,
    MediaDistribution,
    NationalSquad,
    NationalSquadSelector,
    OwnerProfile,
    PromotionMovement,
    SquadMember,
)
from .engine import SimulationEngine
from .football import (
    ClubRoster,
    DomesticLeague,
    FootballWorld,
    InternationalQualifiers,
    MatchResult,
    Player,
    Standing,
)
from .generational_economy import (
    AcademyIntakeRecord,
    AcademyLifecycleSystem,
    GenerationalEconomy,
    GenerationalWorld,
    InsolvencyRecord,
    InsolvencySystem,
    RegistrationAudit,
    RegistrationSystem,
    RetirementRecord,
    SponsorshipContract,
    SponsorshipEvent,
    SponsorshipSystem,
    StadiumFinanceRecord,
    StadiumInvestmentRecord,
    StadiumProfile,
    StadiumSystem,
)
from .governed_politics import GovernedPoliticalEconomy
from .governance import (
    AnnualFinanceReport,
    DecisionOption,
    DecisionRecord,
    GovernanceDecision,
)
from .market import TransferMarket, TransferPolicy, TransferRecord
from .ordered_contracts import OrderedContractMarket
from .policy_registration import StrictRegistrationSystem
from .political_economy import (
    AGENDA_DECISIONS,
    AgendaOutcome,
    PoliticalEconomy,
    PoliticalEvent,
    PoliticalPromise,
    PoliticalReview,
    StakeholderProfile,
    YearArchive,
)
from .political_workload import PolicyWorkloadManager
from .programs import CoachEducationGrant, YouthMatchGrant
from .scenario import build_2026_scenario

__all__ = [
    "AGENDA_DECISIONS",
    "AcademyIntakeRecord",
    "AcademyLifecycleSystem",
    "AdministrationRecord",
    "AdvancedClubWorld",
    "AgendaOutcome",
    "AnnualFinanceReport",
    "Campaign",
    "Club",
    "ClubPyramid",
    "ClubPyramidWorld",
    "ClubRoster",
    "CoachEducationGrant",
    "ContinentalChampionsCup",
    "ContinentalSummary",
    "ContractMarket",
    "ContractRecord",
    "DecisionOption",
    "DecisionRecord",
    "DeepCampaign",
    "DivisionLeague",
    "DomesticCup",
    "DomesticLeague",
    "FootballWorld",
    "GenerationalEconomy",
    "GenerationalWorld",
    "GovernanceDecision",
    "GovernedPoliticalEconomy",
    "InsolvencyRecord",
    "InsolvencySystem",
    "InternationalQualifiers",
    "KnockoutResult",
    "LoanRecord",
    "MatchResult",
    "MediaDistribution",
    "NationalFootballSystem",
    "NationalSquad",
    "NationalSquadSelector",
    "OrderedContractMarket",
    "OwnerProfile",
    "Player",
    "PolicyWorkloadManager",
    "PoliticalEconomy",
    "PoliticalEvent",
    "PoliticalPromise",
    "PoliticalReview",
    "PresidentialPlan",
    "PromotionMovement",
    "Region",
    "RegistrationAudit",
    "RegistrationSystem",
    "RetirementRecord",
    "STRATEGIES",
    "SimulationEngine",
    "SponsorshipContract",
    "SponsorshipEvent",
    "SponsorshipSystem",
    "SquadMember",
    "StadiumFinanceRecord",
    "StadiumInvestmentRecord",
    "StadiumProfile",
    "StadiumSystem",
    "StakeholderProfile",
    "Standing",
    "Strategy",
    "StrictRegistrationSystem",
    "TransferMarket",
    "TransferPolicy",
    "TransferRecord",
    "WorkloadManager",
    "WorkloadReport",
    "YearArchive",
    "YouthMatchGrant",
    "build_2026_scenario",
    "build_deep_2026_scenario",
    "run_deep_strategy",
    "run_strategy",
]
