"""Football Republic public package API."""

from .advanced_ecosystem import (
    AdvancedClubWorld,
    ContinentalChampionsCup,
    ContinentalSummary,
    ContractMarket,
    ContractRecord,
    DomesticCup,
    KnockoutResult,
    LoanRecord,
    WorkloadManager,
    WorkloadReport,
)
from .campaign import Campaign, PresidentialPlan, STRATEGIES, Strategy, run_strategy
from .chairman_career import (
    BriefingItem,
    ChairmanCareer,
    ChairmanLegacyReport,
    OfficialAssessment,
    StakeholderSignal,
)
from .coalition_elections import (
    BlocVote,
    CoalitionCommitment,
    CoalitionCrisisRecord,
    ElectionCandidate,
    ElectionConvention,
    ElectionRoundRecord,
    GovernmentAgreement,
)
from .coalition_runtime import CoalitionElectionHistory
from .constitutional import (
    AdministrationSpan,
    AppointmentRecord,
    ConstitutionalEvent,
    ConstitutionalLongTermCampaign,
    OfficialProfile,
)
from .deep_campaign import DeepCampaign, run_deep_strategy
from .deep_scenario import build_deep_2026_scenario
from .domain import Club, NationalFootballSystem, Region
from .ecosystem import (
    AdministrationRecord,
    ClubPyramid,
    ClubPyramidWorld,
    DivisionLeague,
    MediaDistribution,
    NationalSquad,
    NationalSquadSelector,
    OwnerProfile,
    PromotionMovement,
    SquadMember,
)
from .engine import SimulationEngine
from .football import (
    ClubRoster,
    DomesticLeague,
    FootballWorld,
    InternationalQualifiers,
    MatchResult,
    Player,
    Standing,
)
from .generational_economy import (
    AcademyIntakeRecord,
    AcademyLifecycleSystem,
    GenerationalEconomy,
    GenerationalWorld,
    InsolvencyRecord,
    InsolvencySystem,
    RegistrationAudit,
    RegistrationSystem,
    RetirementRecord,
    SponsorshipContract,
    SponsorshipEvent,
    SponsorshipSystem,
    StadiumFinanceRecord,
    StadiumInvestmentRecord,
    StadiumProfile,
    StadiumSystem,
)
from .governed_politics import GovernedPoliticalEconomy
from .governance import (
    AnnualFinanceReport,
    DecisionOption,
    DecisionRecord,
    GovernanceDecision,
)
from .long_term import (
    ClubHistoryRecord,
    LongTermCampaign,
    PlayerHistoryRecord,
    PresidentProfile,
    SeasonHistoryRecord,
    TermRecord,
)
from .market import TransferMarket, TransferPolicy, TransferRecord
from .ordered_contracts import OrderedContractMarket
from .patronage_justice import (
    CareerEvent,
    CareerPosting,
    JusticeCase,
    JusticeEvent,
    PatronageTie,
    PoliticalPerson,
)
from .patronage_runtime import CareerJusticeHistory
from .policy_registration import StrictRegistrationSystem
from .political_economy import (
    AGENDA_DECISIONS,
    AgendaOutcome,
    PoliticalEconomy,
    PoliticalEvent,
    PoliticalPromise,
    PoliticalReview,
    StakeholderProfile,
    YearArchive,
)
from .political_workload import PolicyWorkloadManager
from .programs import CoachEducationGrant, YouthMatchGrant
from .scenario import build_2026_scenario
from .scenario_history import ReplayableConstitutionalHistory

__all__ = [
    "AGENDA_DECISIONS",
    "AcademyIntakeRecord",
    "AcademyLifecycleSystem",
    "AdministrationRecord",
    "AdministrationSpan",
    "AdvancedClubWorld",
    "AgendaOutcome",
    "AnnualFinanceReport",
    "AppointmentRecord",
    "BlocVote",
    "BriefingItem",
    "Campaign",
    "CareerEvent",
    "CareerJusticeHistory",
    "CareerPosting",
    "ChairmanCareer",
    "ChairmanLegacyReport",
    "Club",
    "ClubHistoryRecord",
    "ClubPyramid",
    "ClubPyramidWorld",
    "ClubRoster",
    "CoachEducationGrant",
    "CoalitionCommitment",
    "CoalitionCrisisRecord",
    "CoalitionElectionHistory",
    "ConstitutionalEvent",
    "ConstitutionalLongTermCampaign",
    "ContinentalChampionsCup",
    "ContinentalSummary",
    "ContractMarket",
    "ContractRecord",
    "DecisionOption",
    "DecisionRecord",
    "DeepCampaign",
    "DivisionLeague",
    "DomesticCup",
    "DomesticLeague",
    "ElectionCandidate",
    "ElectionConvention",
    "ElectionRoundRecord",
    "FootballWorld",
    "GenerationalEconomy",
    "GenerationalWorld",
    "GovernanceDecision",
    "GovernedPoliticalEconomy",
    "GovernmentAgreement",
    "InsolvencyRecord",
    "InsolvencySystem",
    "InternationalQualifiers",
    "JusticeCase",
    "JusticeEvent",
    "KnockoutResult",
    "LoanRecord",
    "LongTermCampaign",
    "MatchResult",
    "MediaDistribution",
    "NationalFootballSystem",
    "NationalSquad",
    "NationalSquadSelector",
    "OfficialAssessment",
    "OfficialProfile",
    "OrderedContractMarket",
    "OwnerProfile",
    "PatronageTie",
    "Player",
    "PlayerHistoryRecord",
    "PolicyWorkloadManager",
    "PoliticalEconomy",
    "PoliticalEvent",
    "PoliticalPerson",
    "PoliticalPromise",
    "PoliticalReview",
    "PresidentProfile",
    "PresidentialPlan",
    "PromotionMovement",
    "Region",
    "RegistrationAudit",
    "RegistrationSystem",
    "ReplayableConstitutionalHistory",
    "RetirementRecord",
    "STRATEGIES",
    "SeasonHistoryRecord",
    "SimulationEngine",
    "SponsorshipContract",
    "SponsorshipEvent",
    "SponsorshipSystem",
    "SquadMember",
    "StadiumFinanceRecord",
    "StadiumInvestmentRecord",
    "StadiumProfile",
    "StadiumSystem",
    "StakeholderProfile",
    "StakeholderSignal",
    "Standing",
    "Strategy",
    "StrictRegistrationSystem",
    "TermRecord",
    "TransferMarket",
    "TransferPolicy",
    "TransferRecord",
    "WorkloadManager",
    "WorkloadReport",
    "YearArchive",
    "YouthMatchGrant",
    "build_2026_scenario",
    "build_deep_2026_scenario",
    "run_deep_strategy",
    "run_strategy",
]
