  function guestData(){const f=currentFixture();const base=[["周岑","国家体育总署副署长","关注国家队结果与协会治理"],["秦川","前国家队队长","代表技术传统与退役球员意见"],["曹禹","国家转播平台总监","关注镜头与现场叙事"]];if(f)base.push([f.opponent.slice(0,1)+"原",`${f.opponent}足协主席`,`关注${f.venue==="home"?"客队礼宾":"主场接待"}与赛后关系`]);const extra={formal:[["贺明卓","职业联盟主席","关注国脚征调与联赛利益"]],supporters:[["程晓雨","校园足球教练","代表基层教练与青训家庭"],["傅宁","国家队球迷协会代表","关注票务与球迷尊重"]],showcase:[["顾文韬","战略合作企业总裁","关注赞助权益与国家形象"]]};return base.concat(extra[state.choices.arrival]||[]);}
  function renderGuests(){const list=document.querySelector("#guestList");if(!state.choices.arrival){list.innerHTML=`<div class="empty">本场尚未确定现场方案。</div>`;document.querySelector("#boxSummary").textContent="来宾名单将在主席确认现场方案后形成。";return;}const guests=guestData();list.innerHTML=guests.map(([n,r,i])=>`<div class="guest"><div class="guest-avatar">${n[0]}</div><div><b>${n} · ${r}</b><span>${i}</span></div></div>`).join("");document.querySelector("#boxSummary").textContent=`${guests.length}名具名来宾进入本场关系网络。`;}
  function renderTimeline(){const f=currentFixture(),container=document.querySelector("#timeline");const events=state.matchEvents||[];if(!events.length||state.eventIndex===0)container.innerHTML=`<div class="empty">比赛尚未开始。主席完成赛前责任后可以推进现场。</div>`;else container.innerHTML=events.slice(0,state.eventIndex).map(e=>`<div class="event ${e.kind}"><b>${e.minute}</b><span>${e.text}</span></div>`).join("");const last=state.eventIndex?events[state.eventIndex-1]:null;document.querySelector("#homeTeam").textContent=f?(f.venue==="home"?"龙华国家队":`${f.opponent}国家队`):"龙华国家队";document.querySelector("#awayTeam").textContent=f?(f.venue==="home"?`${f.opponent}国家队`:"龙华国家队"):"对手";document.querySelector("#homeScore").textContent=last?last.home:0;document.querySelector("#awayScore").textContent=last?last.away:0;document.querySelector("#scoreKicker").textContent=f?`QUALIFIER · CAMPAIGN ${state.campaign} · ROUND ${state.round+1}`:"QUALIFIER";document.querySelector("#matchClock").textContent=state.phase==="match"?(last?`${last.minute} · 比赛进行中`:"等待开球"):['post','mixed','review','between'].includes(state.phase)?"全场结束":"等待主席完成赛前责任";const btn=document.querySelector("#advanceMatchButton");btn.disabled=state.phase!=="match";btn.textContent=state.eventIndex===0?"比赛开球":state.eventIndex<events.length?"推进到下一现场节点":"比赛已经结束";}
  function advanceMatch(){if(state.phase!=="match")return;const event=state.matchEvents[state.eventIndex];if(!event)return;state.eventIndex++;if(event.kind==="goal-home"||event.kind==="goal-away")record(`${event.minute} 比赛出现进球，主席包厢进入直播镜头。`);if(event.kind==="full"){settleMatch();state.phase="post";state.selected=null;save();switchView("office");return;}save();}
  function renderCommand(){const f=currentFixture();document.querySelector("#squadLede").textContent=f?`主教练${state.coachName}已为第${state.round+1}轮独立提交25人名单。主席可以追问医疗和征调程序，不能替换球员。`:"本届比赛结束，技术部门正在维护长期球员池。";const high=state.fatigue>=55;document.querySelector("#squadBrief").innerHTML=`<div class="record"><time>名单结构</time><p>门将3人、后卫8人、中场8人、前锋6人。名单由主教练独立决定。</p></div><div class="record"><time>医疗与负荷</time><p>${high?"多名国脚俱乐部出场负荷偏高，本轮征调冲突概率上升。":"当前医疗风险可控，联合医疗组未建议大规模减员。"}</p></div><div class="record"><time>俱乐部关系</time><p>协会与职业俱乐部关系处于“${metricLabel(state.clubRelations)}”状态，过去的征调方式会影响本轮合作。</p></div>`;document.querySelector("#coachQuote").innerHTML=`<b>主教练${state.coachName}：</b>“我接受主席对资源、程序和结果的追问；具体用谁、怎么踢，由教练组承担。”`;}
  function renderCampaign(){const rows=sortedTable();document.querySelector("#campaignTitle").textContent=`第${state.campaign}届预选赛 · ${state.round>=10?"已结束":`第${state.round+1}轮`}`;document.querySelector("#tableArea").innerHTML=`<table class="table"><thead><tr><th>球队</th><th>场</th><th>胜</th><th>平</th><th>负</th><th>净胜</th><th>分</th></tr></thead><tbody>${rows.map(t=>`<tr class="${t.name==="龙华"?"user":""}"><td>${rows.indexOf(t)+1}. ${t.name}</td><td>${t.p}</td><td>${t.w}</td><td>${t.d}</td><td>${t.l}</td><td>${t.gf-t.ga}</td><td><b>${t.pts}</b></td></tr>`).join("")}</tbody></table>`;document.querySelector("#scheduleList").innerHTML=baseFixtures.map((f,i)=>{const h=state.matchHistory.find(m=>m.campaign===state.campaign&&m.round===i+1);return `<div class="fixture ${i===state.round&&state.round<10?"current":""} ${h?"done":""}"><div class="round">R${i+1}</div><div><b>${f.venue==="home"?"主场":"客场"} · ${f.opponent}</b><p>${campaignDate(f)} · ${f.city}</p></div><div class="score">${h?`${h.ourGoals}—${h.oppGoals}`:i===state.round?"当前":"待赛"}</div></div>`;}).join("");const hist=state.matchHistory.slice().reverse();document.querySelector("#matchHistory").innerHTML=hist.length?hist.map(h=>`<div class="record"><time>第${h.campaign}届 · 第${h.round}轮 · ${h.outcome}</time><p>龙华 ${h.ourGoals}—${h.oppGoals} ${h.opponent} · xG ${h.xg} · 赛后${h.points}分 · 主教练${h.coach}</p></div>`).join(""):`<div class="empty">尚无正式比赛记录。</div>`;}
  function renderArchive(){document.querySelector("#archiveList").innerHTML=state.records.slice().reverse().map(r=>`<div class="record"><time>${r.time}</time><p>${r.text}</p></div>`).join("");renderMetrics(document.querySelector("#metricsArchive"));document.querySelector("#endNotice").textContent=state.phase==="campaign_complete"?`第${state.campaign}届已经完成，可以保留长期后果继续下一届。`:`当前进行到第${state.campaign}届第${Math.min(state.round+1,10)}轮；此前比赛与决策均已保留。`;}
  function renderAll(){renderHeader();renderStages();renderBrief();renderAction();renderGuests();renderTimeline();renderCommand();renderCampaign();renderArchive();renderMetrics(document.querySelector("#metricsCommand"));}
  function switchView(view){document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));document.querySelectorAll(".scene").forEach(s=>s.classList.remove("active"));const map={office:"officeScene",command:"commandScene",stadium:"stadiumScene",campaign:"campaignScene",archive:"archiveScene"};document.querySelector("#"+map[view]).classList.add("active");const titles={office:["主席办公室 · 国家队窗口","连续预选赛生涯，前一场的后果会进入下一场。"],command:["国家队指挥中心","技术团队独立比赛，主席管理制度、资源与责任。"],stadium:["比赛现场 · 主席包厢","你可以经历比赛，但不能越级指挥主教练。"],campaign:["预选赛战报","十轮赛程、积分榜和历史赛果持续更新。"],archive:["主席连续决策档案","所有选择按照发生顺序保存在本机。"]};document.querySelector("#pageTitle").textContent=titles[view][0];document.querySelector("#pageSubtitle").textContent=titles[view][1];}

  document.querySelectorAll(".nav-button").forEach(btn=>btn.addEventListener("click",()=>switchView(btn.dataset.view)));
  document.querySelector("#advanceMatchButton").addEventListener("click",advanceMatch);
  document.querySelector("#resetButton").addEventListener("click",()=>{if(confirm("确定清空整个连续主席生涯并重新开始吗？")){localStorage.removeItem(STORAGE_KEY);state=clone(defaults);ensureTable();save();switchView("office");}});
  renderAll();if(state.phase==="match")switchView("stadium");
