const stakeholderNames = {
  ministry:"国家体育主管部门",clubs:"职业俱乐部联盟",players:"球员与工会",localFAs:"地方足协",
  sponsors:"转播与赞助商",supporters:"球迷与公众",coaches:"教练员群体",referees:"裁判委员会"
};
const ecologyNames = {
  clubSolvency:"俱乐部偿付能力",wageSecurity:"工资保障",youthPipeline:"青训人才管道",domesticMinutes:"本土球员出场",
  coachingQuality:"教练培养质量",refereeTrust:"裁判公信力",leagueCommerce:"联赛商业健康",grassrootsReach:"基层覆盖",
  womenFootball:"女足发展",stadiumSafety:"体育场安全",calendarHealth:"赛历健康",starRetention:"球星留存"
};
const rolloutOptions = {
  pilot:{title:"区域试点",body:"先在部分联赛和地方足协试行。阻力较小、成本较低，但见效慢且容易形成地区差异。",costMultiplier:.55,effectMultiplier:.55,lagDelta:2,politics:0,media:-1},
  phased:{title:"分阶段全国实施",body:"先发布统一标准，再按赛季分批落地。执行稳定，成本和阻力均衡。",costMultiplier:1,effectMultiplier:1,lagDelta:1,politics:1,media:0},
  national:{title:"全国同步强推",body:"立即统一规则和审计，短期冲击最大。需要足够政治资本与执行资源。",costMultiplier:1.55,effectMultiplier:1.35,lagDelta:0,politics:3,media:3}
};
const policyCatalog = {
  clubLicensing:{
    name:"职业俱乐部准入与退出",department:"职业联赛部",problem:"部分俱乐部依赖股东输血，欠税、欠薪和突然退出会破坏整个赛季。",
    indicator:"clubSolvency",supporters:["ministry","players","supporters"],opponents:["clubs","localFAs"],
    models:{
      disclosure:{title:"强化信息披露",body:"季度公开审计、关联交易和债务结构，暂不设置硬性资本门槛。",cost:1.1,lag:2,effects:{clubSolvency:4,wageSecurity:2,leagueCommerce:2},stakeholders:{clubs:-2,ministry:2,sponsors:2,supporters:2}},
      bond:{title:"准入保证金与退出基金",body:"按联赛级别缴纳工资保证金和赛季退出基金，弱俱乐部成本上升。",cost:2.8,lag:3,effects:{clubSolvency:8,wageSecurity:8,leagueCommerce:3},stakeholders:{clubs:-7,players:6,ministry:4,supporters:4,localFAs:-2}},
      hardCap:{title:"资本充足率硬门槛",body:"连续两季不达标即降级或退出。能清理风险，也可能短期造成多队降级。",cost:3.4,lag:2,effects:{clubSolvency:12,wageSecurity:7,leagueCommerce:-2,starRetention:-2},stakeholders:{clubs:-12,localFAs:-7,ministry:6,players:5,supporters:1}}
    }
  },
  wageSecurity:{
    name:"球员工资保障制度",department:"注册与劳动关系部",problem:"欠薪会导致罢训、仲裁和自由身潮，国家队征调也会被俱乐部危机污染。",
    indicator:"wageSecurity",supporters:["players","supporters","ministry"],opponents:["clubs"],
    models:{
      arbitration:{title:"快速仲裁通道",body:"建立30天内裁决的欠薪仲裁庭，但不直接垫付工资。",cost:1.4,lag:1,effects:{wageSecurity:5,clubSolvency:1},stakeholders:{players:5,clubs:-3,ministry:2}},
      escrow:{title:"工资专户与月度审计",body:"俱乐部必须把未来三个月工资存入监管专户。",cost:2.6,lag:2,effects:{wageSecurity:10,clubSolvency:5,starRetention:2},stakeholders:{players:8,clubs:-8,sponsors:2,supporters:4}},
      guarantee:{title:"中央工资保障基金",body:"足协先行垫付基本工资，再向股东和地方追偿。财政压力大，但能阻止联赛停摆。",cost:5.2,lag:1,effects:{wageSecurity:14,clubSolvency:2,leagueCommerce:4},stakeholders:{players:10,clubs:2,ministry:-2,supporters:6}}
    }
  },
  youthDevelopment:{
    name:"青训补偿与本土人才",department:"青少年足球部",problem:"基层培养者得不到回报，职业俱乐部倾向购买成品球员，人才管道逐年变窄。",
    indicator:"youthPipeline",supporters:["localFAs","coaches","supporters"],opponents:["clubs"],
    models:{
      compensation:{title:"训练补偿与联合机制",body:"职业签约和转会时向12—21岁培养单位按年限支付补偿。",cost:1.8,lag:3,effects:{youthPipeline:7,grassrootsReach:4,domesticMinutes:2},stakeholders:{localFAs:6,coaches:5,clubs:-4}},
      homegrown:{title:"本土培养名额",body:"一线队报名必须包含本俱乐部培养球员，并设置最低出场激励。",cost:2.2,lag:4,effects:{youthPipeline:8,domesticMinutes:9,starRetention:-2},stakeholders:{clubs:-6,coaches:6,supporters:4}},
      academyNetwork:{title:"国家区域青训网络",body:"足协直接资助区域学院、数据共享和跨地区选材，地方足协必须接受统一审计。",cost:6.0,lag:5,effects:{youthPipeline:15,grassrootsReach:10,coachingQuality:4},stakeholders:{localFAs:-3,coaches:8,ministry:5,supporters:5}}
    }
  },
  foreignPlayers:{
    name:"外援与本土出场政策",department:"职业联赛部",problem:"外援能提高比赛质量与商业价值，但过度依赖会挤压本土关键位置。",
    indicator:"domesticMinutes",supporters:["coaches","supporters"],opponents:["clubs","sponsors"],
    models:{
      open:{title:"开放注册、限制同时出场",body:"允许更多外援注册，但比赛中同时出场人数受限。",cost:.6,lag:1,effects:{leagueCommerce:5,starRetention:4,domesticMinutes:-3},stakeholders:{clubs:5,sponsors:5,coaches:-2}},
      balanced:{title:"位置与年龄差异化配额",body:"中轴线和U23位置设置差异化规则，兼顾比赛质量与培养空间。",cost:1.2,lag:2,effects:{domesticMinutes:5,youthPipeline:3,leagueCommerce:1},stakeholders:{clubs:-2,coaches:4,supporters:2}},
      domestic:{title:"强制本土核心名额",body:"每场必须保持多名本土培养球员在场，短期比赛质量和商业吸引力可能下降。",cost:1.6,lag:2,effects:{domesticMinutes:11,youthPipeline:5,leagueCommerce:-5,starRetention:-4},stakeholders:{clubs:-7,sponsors:-6,coaches:6,supporters:3}}
    }
  },
  refereeGovernance:{
    name:"裁判独立与技术治理",department:"裁判委员会",problem:"俱乐部、地方关系和模糊判罚会侵蚀联赛公信力，单纯处罚个别裁判无法解决制度问题。",
    indicator:"refereeTrust",supporters:["supporters","sponsors","ministry"],opponents:["clubs","referees"],
    models:{
      publish:{title:"关键判罚说明制度",body:"赛后公布关键判罚依据和VAR音频摘要。",cost:1.0,lag:1,effects:{refereeTrust:6,leagueCommerce:2},stakeholders:{supporters:5,sponsors:2,referees:-2}},
      independent:{title:"独立裁判公司",body:"从足协竞赛部门剥离选派、考核和报酬，建立外部监督委员会。",cost:3.0,lag:3,effects:{refereeTrust:12,leagueCommerce:4},stakeholders:{referees:-5,clubs:-3,ministry:5,supporters:7}},
      professional:{title:"全职职业裁判体系",body:"提高薪酬、集中训练、公开评级并引入国际交流。",cost:5.0,lag:4,effects:{refereeTrust:15,leagueCommerce:5,coachingQuality:1},stakeholders:{referees:8,sponsors:3,ministry:3,supporters:6}}
    }
  },
  broadcasting:{
    name:"转播权与收入分配",department:"商业与媒体部",problem:"豪门和弱队对分配方式冲突，短期收入最大化可能扩大竞争失衡。",
    indicator:"leagueCommerce",supporters:["sponsors","clubs"],opponents:["clubs","localFAs"],
    models:{
      market:{title:"市场表现优先分配",body:"收视、排名和商业贡献占主要权重，强队收入更高。",cost:.8,lag:1,effects:{leagueCommerce:8,clubSolvency:-3},stakeholders:{sponsors:7,clubs:3,supporters:-2}},
      balanced:{title:"保底加绩效分配",body:"一半平均分配，一半按排名、青训和收视绩效分配。",cost:1.3,lag:2,effects:{leagueCommerce:5,clubSolvency:5,youthPipeline:2},stakeholders:{clubs:1,sponsors:3,localFAs:2}},
      solidarity:{title:"竞争平衡与基层反哺",body:"提高平均分配和基层足球提取比例，豪门商业收益被压缩。",cost:2.1,lag:2,effects:{clubSolvency:8,grassrootsReach:7,leagueCommerce:1},stakeholders:{clubs:-5,localFAs:7,supporters:3,sponsors:-2}}
    }
  },
  coachLicensing:{
    name:"教练员培养与准入",department:"技术发展部",problem:"基层教练数量不足，职业教练培训与实际岗位脱节，优秀年轻教练缺乏晋升通道。",
    indicator:"coachingQuality",supporters:["coaches","localFAs"],opponents:["clubs"],
    models:{
      credits:{title:"继续教育学分制",body:"所有持证教练每年完成战术、体能、儿童保护和数据课程。",cost:1.2,lag:2,effects:{coachingQuality:6,youthPipeline:2},stakeholders:{coaches:-1,clubs:-1,ministry:2}},
      pathway:{title:"分级岗位晋升通道",body:"青年队、女足、低级别联赛与顶级联赛形成可验证的晋升路径。",cost:2.4,lag:3,effects:{coachingQuality:10,youthPipeline:4,womenFootball:3},stakeholders:{coaches:7,clubs:-2,localFAs:4}},
      institute:{title:"国家教练学院",body:"长期脱产培养、海外交流和本土案例库并行，成本高但形成技术积累。",cost:5.5,lag:5,effects:{coachingQuality:16,youthPipeline:6,domesticMinutes:2},stakeholders:{coaches:9,ministry:4,supporters:2}}
    }
  },
  schoolFootball:{
    name:"校园与基层足球",department:"群众足球部",problem:"学校、地方足协和职业青训各自为政，孩子跨体系流动困难，基层比赛不足。",
    indicator:"grassrootsReach",supporters:["localFAs","supporters","coaches"],opponents:["ministry"],
    models:{
      leagues:{title:"县市校园联赛网络",body:"资助常态化校际联赛和保险，不直接统一训练体系。",cost:2.5,lag:3,effects:{grassrootsReach:8,youthPipeline:4},stakeholders:{localFAs:5,supporters:4}},
      registration:{title:"统一球员注册与升学档案",body:"打通学校、地方足协和俱乐部注册，减少重复注册和人才截留。",cost:3.2,lag:3,effects:{grassrootsReach:7,youthPipeline:8},stakeholders:{localFAs:-2,clubs:2,coaches:5,ministry:2}},
      universal:{title:"全国校园足球基础保障",body:"场地、教练、保险、竞赛和升学评价一体化推进，财政和跨部门协调压力极高。",cost:8.0,lag:5,effects:{grassrootsReach:17,youthPipeline:12,coachingQuality:3},stakeholders:{ministry:-3,localFAs:7,supporters:8,coaches:6}}
    }
  },
  womenFootball:{
    name:"女足联赛与国家队基础",department:"女子足球部",problem:"女足俱乐部依附男足主体，职业合同、转播和青训投入不稳定。",
    indicator:"womenFootball",supporters:["players","supporters","ministry"],opponents:["clubs","sponsors"],
    models:{
      minimum:{title:"女足准入最低投入",body:"顶级男足俱乐部必须维持女足或缴纳专项发展金。",cost:1.8,lag:2,effects:{womenFootball:7,grassrootsReach:2},stakeholders:{clubs:-5,players:5,ministry:3}},
      league:{title:"独立女足职业联盟",body:"独立准入、赛历、商业和工资保障，减少对男足母公司的依赖。",cost:4.0,lag:4,effects:{womenFootball:13,wageSecurity:3,leagueCommerce:1},stakeholders:{players:8,clubs:-3,sponsors:2,supporters:4}},
      national:{title:"女足国家发展计划",body:"校园、青训、职业联赛和国家队保障一体化投入。",cost:7.0,lag:5,effects:{womenFootball:18,grassrootsReach:6,coachingQuality:3},stakeholders:{players:10,ministry:5,supporters:6}}
    }
  },
  stadiumSafety:{
    name:"体育场安全与球迷服务",department:"赛事安全部",problem:"老旧场馆、安检外包和客队球迷隔离标准不一，事故会迅速变成政治危机。",
    indicator:"stadiumSafety",supporters:["supporters","ministry","sponsors"],opponents:["clubs","localFAs"],
    models:{
      audit:{title:"全国场馆风险审计",body:"统一检查疏散、消防、安保合同和客队区，不直接承担改造费用。",cost:1.5,lag:1,effects:{stadiumSafety:7},stakeholders:{clubs:-2,localFAs:-2,ministry:4}},
      fund:{title:"安全改造配套基金",body:"足协与地方共同出资改造高风险场馆，按审计优先级拨款。",cost:5.0,lag:3,effects:{stadiumSafety:13,leagueCommerce:3},stakeholders:{localFAs:5,clubs:3,ministry:2,supporters:5}},
      licensing:{title:"不达标即关闭看台",body:"未完成整改的场馆必须空场或异地比赛，安全提升最快但地方阻力巨大。",cost:2.8,lag:1,effects:{stadiumSafety:16,leagueCommerce:-3},stakeholders:{clubs:-8,localFAs:-9,ministry:6,supporters:3}}
    }
  },
  calendar:{
    name:"赛历、国家队窗口与球员负荷",department:"竞赛管理部",problem:"联赛、杯赛、洲际赛事和国家队窗口叠加，俱乐部与国家队长期争夺球员身体。",
    indicator:"calendarHealth",supporters:["players","coaches","clubs"],opponents:["sponsors"],
    models:{
      coordination:{title:"赛历联合委员会",body:"职业联盟、国家队和转播方共同确认全年窗口，减少临时改期。",cost:1.0,lag:1,effects:{calendarHealth:6,wageSecurity:1},stakeholders:{clubs:4,players:4,sponsors:-1}},
      protected:{title:"国家队与休赛保护期",body:"设置最低休息天数和不可挤占的国家队集训期。",cost:1.8,lag:2,effects:{calendarHealth:11,starRetention:2},stakeholders:{players:7,coaches:5,clubs:1,sponsors:-4}},
      contraction:{title:"压缩联赛与杯赛场次",body:"减少比赛总量，显著改善负荷，但转播和票房收入下降。",cost:2.0,lag:2,effects:{calendarHealth:17,leagueCommerce:-7,starRetention:4},stakeholders:{players:9,coaches:7,sponsors:-9,clubs:-3}}
    }
  },
  financialControl:{
    name:"薪资成本与转会监管",department:"财务监管部",problem:"军备竞赛抬高工资和转会费，俱乐部风险在成绩压力下不断积累。",
    indicator:"starRetention",supporters:["ministry","supporters"],opponents:["clubs","players","sponsors"],
    models:{
      transparency:{title:"工资与经纪费透明",body:"公布俱乐部工资总额区间、经纪费和关联方转会。",cost:1.0,lag:1,effects:{clubSolvency:4,starRetention:-1,leagueCommerce:1},stakeholders:{clubs:-3,players:-2,supporters:3}},
      ratio:{title:"足球支出占收入比例",body:"工资、转会摊销和经纪费不得超过经审计收入的一定比例。",cost:2.5,lag:3,effects:{clubSolvency:10,wageSecurity:5,starRetention:-4},stakeholders:{clubs:-8,players:-5,ministry:5}},
      tax:{title:"奢侈税与竞争平衡基金",body:"允许高支出，但超额部分缴纳奢侈税反哺弱队和青训。",cost:1.8,lag:2,effects:{clubSolvency:6,youthPipeline:4,starRetention:1},stakeholders:{clubs:-4,players:1,localFAs:4,supporters:3}}
    }
  }
};
const incidentCatalog = {
  wageArrears:{
    title:"三家职业俱乐部出现连续欠薪",body:"球员工会准备公开停训名单，地方政府要求足协避免联赛停摆。",
    options:{
      enforce:{title:"启动工资专户审计并扣除联赛分红",body:"快速维护规则，但可能直接压垮现金流最弱的俱乐部。",effects:{wageSecurity:6,clubSolvency:-3},stakeholders:{players:6,clubs:-6,ministry:2},system:{fan:2,media:-1,club:-4}},
      bridge:{title:"提供有条件过桥资金",body:"足协垫付基本工资，股东提供担保并接受资产冻结。",cost:4.0,effects:{wageSecurity:8,clubSolvency:3},stakeholders:{players:7,clubs:3,ministry:-2},system:{fan:1,media:-2}},
      mediate:{title:"地方协调，不公开处罚",body:"短期避免停赛，但规则信誉和后续执行力下降。",effects:{wageSecurity:-4,refereeTrust:-1},stakeholders:{clubs:4,players:-7,localFAs:5},system:{fan:-3,media:5,politics:-2}}
    }
  },
  refereeLeak:{
    title:"裁判选派内部沟通记录泄露",body:"记录显示个别俱乐部高层曾试图影响裁判安排，媒体要求公开全部名单。",
    options:{
      independent:{title:"外部调查并暂停涉事人员",body:"牺牲短期稳定，换取独立调查的可信度。",cost:1.5,effects:{refereeTrust:9},stakeholders:{clubs:-5,referees:-3,supporters:7,ministry:3},system:{fan:3,media:-3}},
      internal:{title:"内部纪律调查",body:"控制信息范围，避免扩大冲突，但公众可能认为足协自查自纠。",effects:{refereeTrust:2},stakeholders:{clubs:1,referees:2,supporters:-3},system:{media:3}},
      deny:{title:"否认存在系统性问题",body:"保护现有体系，若后续出现新证据，政治代价会被放大。",effects:{refereeTrust:-7},stakeholders:{clubs:3,referees:4,supporters:-8},system:{fan:-4,media:7,politics:-3}}
    }
  },
  stadiumIncident:{
    title:"联赛看台发生拥挤踩踏险情",body:"无人死亡，但视频显示疏散通道被商业设施占用，地方足协此前审计流于形式。",
    options:{
      close:{title:"立即关闭高风险看台并全国复查",body:"安全优先，部分比赛将空场或异地进行。",cost:2.2,effects:{stadiumSafety:10,leagueCommerce:-3},stakeholders:{supporters:5,clubs:-5,localFAs:-6,ministry:5},system:{fan:2,media:-2}},
      fund:{title:"设立紧急整改基金",body:"给地方和俱乐部整改窗口，但足协承担较高财政成本。",cost:5.0,effects:{stadiumSafety:8,leagueCommerce:1},stakeholders:{clubs:4,localFAs:5,ministry:-1},system:{media:-1}},
      local:{title:"责成地方自行处理",body:"足协避免直接承担成本，但全国标准继续碎片化。",effects:{stadiumSafety:-4},stakeholders:{localFAs:3,supporters:-6},system:{fan:-3,media:5}}
    }
  },
  broadcastDispute:{
    title:"转播平台要求重新谈判分成",body:"平台以收视不及预期为由拖延付款，弱队现金流开始紧张。",
    options:{
      enforce:{title:"执行合同并准备仲裁",body:"维护合同纪律，但可能造成转播中断。",cost:1.2,effects:{leagueCommerce:3,clubSolvency:2},stakeholders:{sponsors:-6,clubs:4,ministry:2},system:{media:2}},
      restructure:{title:"重构保底加绩效分成",body:"接受部分调整，换取付款恢复和长期透明。",effects:{leagueCommerce:6,clubSolvency:4},stakeholders:{sponsors:4,clubs:2,supporters:1},system:{politics:1,media:-2}},
      bailout:{title:"足协先行垫付俱乐部分成",body:"避免联赛现金流断裂，但把商业风险转移到足协。",cost:5.5,effects:{clubSolvency:5,leagueCommerce:-1},stakeholders:{clubs:6,sponsors:3,ministry:-4},system:{politics:-2}}
    }
  },
  academyAbuse:{
    title:"地方青训基地被曝违规收费与体罚",body:"多名家长公开证据，地方足协担心全国统一调查影响招生。",
    options:{
      protect:{title:"儿童保护独立调查",body:"暂停涉事教练执照，开放匿名举报和家长法律援助。",cost:1.8,effects:{youthPipeline:4,grassrootsReach:5,coachingQuality:2},stakeholders:{coaches:-4,localFAs:-4,supporters:8,ministry:4},system:{fan:3,media:-3}},
      rectify:{title:"限期整改并保留基地资格",body:"避免体系突然崩塌，但必须公开整改清单。",cost:.8,effects:{youthPipeline:1,grassrootsReach:1},stakeholders:{localFAs:2,coaches:1,supporters:-2},system:{media:1}},
      suppress:{title:"按个案处理，禁止扩大讨论",body:"短期控制舆情，长期将严重损害基层信任。",effects:{grassrootsReach:-8,youthPipeline:-4},stakeholders:{localFAs:4,supporters:-10},system:{fan:-6,media:8,politics:-3}}
    }
  }
};
